# Notebook 1: Data Loading and Validation

Objective:
- Load raw customer churn data
- Inspect dataset structure
- Validate schema
- Check missing values
- Identify data quality issues

Dataset:
IBM Telco Customer Churn Dataset: customer_data.csv

###  Imports

In [4]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

### Load Dataset

In [8]:
df = pd.read_csv("data/customer_data.csv")

# Preview
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

### Shape

In [7]:
print("Rows: ", df.shape[0])
print("Columns: ", df.shape[1] )

Rows:  7043
Columns:  21

### Column Names

In [10]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

### Data Types

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

### Missing Values

In [12]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

### Duplicate Records

In [13]:
duplicates = df.duplicated().sum()

print("Duplicate rows:", duplicates)

Duplicate rows: 0

### Statistical Summary

In [14]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

### Object Columns

In [16]:
categorical_columns = df.select_dtypes(include=["object", "string"]).columns

print(categorical_columns)

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges',
       'Churn'],
      dtype='str')

### Unique Values

In [17]:
for col in categorical_columns:
    print("\n", col)
    print(df[col].unique())

 customerID
<StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7043, dtype: str

 gender
<StringArray>
['Female', 'Male']
Length: 2, dtype: str

 Partner
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

 Dependents
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 PhoneService
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 MultipleLines
<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str

 InternetService
<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

 OnlineSecurity
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

 OnlineBackup
<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

 DeviceProtection
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

 TechSupport
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

 StreamingTV
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

 StreamingMovies
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

 Contract
<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str

 PaperlessBilling
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

 PaymentMethod
<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

 TotalCharges
<StringArray>
[  '29.85',  '1889.5',  '108.15', '1840.75',  '151.65',   '820.5',  '1949.4',
   '301.9', '3046.05', '3487.95',
 ...
 '2625.25', '6886.25',  '1495.1',   '743.3',  '1419.4',  '1990.5',  '7362.9',
  '346.45',   '306.6',  '6844.5']
Length: 6531, dtype: str

 Churn
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

### Churn Distribution

In [18]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

### Class Percentage

In [19]:
df["Churn"].value_counts(normalize= True)* 100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

### Save Validation Report

In [21]:
validation_report = {
    "row": df.shape[0],
    "columns": df.shape[1],
    "duplicate": duplicates,
    "missing_values": df.isnull().sum().sum()
}
validation_report

{'row': 7043,
 'columns': 21,
 'duplicate': np.int64(0),
 'missing_values': np.int64(0)}

In [22]:
print("Notebook 1 completed successfully.")

Notebook 1 completed successfully.